import { useState, useEffect } from 'react';
import { Calendar, ArrowRight, BookOpen, Home, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Link, useNavigate } from 'react-router-dom';
import breadcrumbBg from '@/assets/breadcums.jpeg';

const BLOGS_API = '/backend/api/current_affairs.php';

interface Blog { id: string | number; title: string; slug?: string; excerpt?: string; content?: string; created_at?: string | null; image_url?: string; cover_image_url?: string; category?: string; author?: string; tags?: string; }
const generateSlug = (title: string) => title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
const getImage = (blog: Blog) => blog.cover_image_url || blog.image_url || '/ght_logo.png';
const getExcerpt = (blog: Blog) => { if (blog.excerpt?.trim()) return blog.excerpt; const text = (blog.content || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim(); return text.length > 160 ? `${text.slice(0, 160)}...` : text; };
const formatDate = (date?: string | null) => date ? new Date(date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '';

export default function Blogs() {
  const [blogs, setBlogs] = useState<Blog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { fetch(BLOGS_API).then(async r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then(d => { if (!d?.success || !Array.isArray(d.data)) throw new Error('Invalid API response'); setBlogs(d.data); }).catch(e => { console.error(e); setError('Unable to load blogs. Please try again later.'); }).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="min-h-screen flex items-center justify-center"><div className="text-center"><div className="animate-spin w-12 h-12 border-4 border-[#101c34] border-t-transparent rounded-full mx-auto mb-4" /><p className="text-gray-600">Loading blogs...</p></div></div>;
  if (error) return <div className="min-h-screen flex items-center justify-center"><div className="text-center max-w-md p-8"><BookOpen className="w-10 h-10 mx-auto mb-4 text-red-500" /><h2 className="text-xl font-semibold text-gray-800 mb-2">Something went wrong</h2><p className="text-gray-600 mb-6">{error}</p><Button onClick={() => window.location.reload()}>Try Again</Button></div></div>;
  return <div className="min-h-screen bg-gradient-to-br from-[#f0f2f7] via-white to-blue-50 overflow-x-hidden"><div className="relative w-full h-64 md:h-80 overflow-hidden"><img src={breadcrumbBg} alt="Blogs" className="absolute inset-0 w-full h-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-[#101c34]/90 via-[#101c34]/55 to-black/25" /><div className="relative h-full flex flex-col justify-end px-6 pb-8 md:px-12 md:pb-10 container mx-auto"><nav className="flex items-center gap-1.5 text-white/70 text-sm mb-3"><Link to="/" className="flex items-center gap-1 hover:text-white"><Home className="w-3.5 h-3.5" />Home</Link><ChevronRight className="w-3.5 h-3.5 text-white/40" /><span className="text-white font-medium">Blogs</span></nav><h1 className="text-3xl md:text-5xl font-extrabold text-white">Our Blog</h1><p className="text-white/70 mt-2 text-sm md:text-base max-w-xl">Insights, stories, and updates from India's premier hospitality platform.</p></div></div><section className="py-6 md:py-12 px-4"><div className="container mx-auto pb-8">{blogs.length === 0 ? <div className="text-center py-12"><BookOpen className="w-8 h-8 text-gray-400 mx-auto mb-4" /><h3 className="text-xl font-semibold text-gray-600">No blogs found</h3></div> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">{blogs.map(blog => { const slug = blog.slug || generateSlug(blog.title); return <Card key={blog.id} className="group hover:shadow-lg transition-all duration-300 bg-white/90 cursor-pointer overflow-hidden flex flex-col" onClick={() => navigate(`/blogs/${slug}`)}><div><img src={getImage(blog)} alt={blog.title} className="w-full h-40 md:h-48 object-cover" loading="lazy" onError={e => { (e.target as HTMLImageElement).src = '/ght_logo.png'; }} /></div><CardHeader className="pb-2 pt-4 px-4"><div className="flex items-center gap-2 mb-2"><Badge variant="outline" className="text-xs bg-[#f0f2f7] text-[#101c34] border-[#b8c0d8]">{blog.category || 'Blog'}</Badge></div><CardTitle className="text-base md:text-lg line-clamp-2">{blog.title}</CardTitle><CardDescription className="text-xs md:text-sm line-clamp-2">{getExcerpt(blog)}</CardDescription></CardHeader><CardContent className="px-4 pb-4 flex-grow flex flex-col justify-between"><div className="flex items-center justify-between text-xs md:text-sm text-gray-500 mb-3">{blog.author && <span className="truncate">By {blog.author}</span>}{blog.created_at && <span className="flex items-center gap-1 whitespace-nowrap"><Calendar className="w-3 h-3" />{formatDate(blog.created_at)}</span>}</div><Button variant="outline" size="sm" className="w-full group-hover:bg-[#f0f2f7] text-xs md:text-sm mt-auto">Read Article<ArrowRight className="w-3 h-3 md:w-4 md:h-4 ml-2" /></Button></CardContent></Card>; })}</div>}</div></section></div>;
}
